### ISSUE TITLE
rtpproxy delay in audio relay when using re-packetization

### ISSUE THREAD

**Issue by crashza** [sippy/rtpproxy#33] opened 2015-08-17 10:37 UTC
Hi, 
I am facing an issue when using the re-packetization feauture of rtpproxy.

When a media session is updated with a Re-Invite audio is only relays about 7 to 15 seconds seconds later.

This only happens when using zNN in opensips script, If i remove the re-packetization audio is passed immediately when on re-invite etc.

This seems to happen whenever a party changes their Source port.

below is an egsample when a 200ok is passed it changes source port in SDB and rtpproxy only relays the packets around 7 seconds later.

http://salamander.iburst.co.za:8000/personal/signalling.txt

I have tried this without bridging i get the same result.

I have also tried rtpproxy-2.0.0 and 1.2.1 with same reults, the only difference is with 2.0.0 when using repacketization the audio is distorted after changing the payload.

Regards
Trevor Steyn

**Comment by crashza** [comment] 2015-08-19 13:20
Anyone have any ideas how i can resolve this issue?

**Comment by sobomax** [comment] 2015-08-24 19:17
Hi, sorry for the delay with the answer. It would be quite helpful is you can run latest rtpproxy (master branch from the github) in the debug mode (i.e. "-f -d dbug") and collect output of one such problematic session. The thing we're mostly interested in is track of commands/replies, which would allow us to construct test case for reproducing the issue. Another way to do it is to run rtpproxy in the UDP command mode and perform packet capture on the control socket and sharing PCAP file with us. Thanks!

**Comment by crashza** [comment] 2015-08-24 21:17
Hi Maksym, No problem on the delay, I have captured the UDP control portion as well as the SIP and RTP, where can i send the pcaps privately?

**Comment by crashza** [comment] 2015-08-24 21:29
Also maybe i should mention i got around the issue by only using the "znn" in one direction let em explain.

if i have my routing in opensips like this.

Routing....
        if (has_body("application/sdp")) {
                if (rtpproxy_offer('iewz20')) {
                        t_on_reply("1");
                } else {
                        t_on_reply("2");
                }
        }
        route(RELAY);
}

onreply_route[1]
{
    if (has_body("application/sdp"))
        rtpproxy_answer('eiwz20');
}

Then i get the delay when rtp is changed at callee but if i change onreply route to the following
onreply_route[1]
{
    if (has_body("application/sdp"))
        rtpproxy_answer('eiw');
}

Then there is no delay when audio is routed, so it seems the issue is only observed when re-packetization option exists in both directions.

As my current project only requires the change in payload from one specific vendor i can work around this but will more than gladly provide any info you guys need to solve the issue.

Regards
Trevor Steyn

**Comment by sobomax** [comment] 2015-08-24 22:49
> I have captured the UDP control portion as well as the SIP and RTP, where can i send the pcaps privately?

Great, drop them to sobomax@sippysoft.com. I will try to take a look in the next day or two. Thanks!

**Comment by crashza** [comment] 2015-08-28 10:55
HI Maksym. 
Just want to find out if you need any more info, where the traces sufficient?

Regards
Trevor Steyn

**Comment by sobomax** [comment] 2015-08-28 16:24
I've received those, thanks, have not got time to look in details yet. But
I definitely will soon.


On Fri, Aug 28, 2015 at 3:55 AM, Trevor Steyn <notifications@github.com>
wrote:

> HI Maksym.
> Just want to find out if you need any more info, where the traces
> sufficient?
>
> Regards
> Trevor Steyn
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sippy/rtpproxy/issues/33#issuecomment-135739392>.
>



-- 
Maksym Sobolyev
Sippy Software, Inc.
Internet Telephony (VoIP) Experts
Tel (Canada): +1-778-783-0474
Tel (Toll-Free): +1-855-747-7779
Fax: +1-866-857-6942
Web: http://www.sippysoft.com
MSN: sales@sippysoft.com
Skype: SippySoft

**Comment by sobomax** [comment] 2015-09-01 22:16
Hi Trevor, thank you for reporting the issue and sending the relevant captures. It helped a lot since the issue had to do with the stream starting to come from different source with different SSRC, something that would not be easily seen from the logs alone. Please update your rtpproxy to include change d1b61a5cdeef173566366a431bbf31297bcf00de and repeat your tests. Let me know if it resolves the issue so that I can close this ticket. I am also thinking of how we can get this tested as part of the CI process. Thanks!

**Comment by crashza** [comment] 2015-09-02 10:59
Hi Maksym, The fix works and media is now sent correctly however when using the new version Audio quality after being resampled from 60ms to 20ms is terrible and i cant understand why, I have analysed the RTP and all looks ok regarding Jitter, Any reason i would be having quality issues between master and version 1.2.1 that is available in EPEL repo for EL6? The difference in quality is night and day, I have sent 2 pcaps of the calls to you email just in the event you want to check them.

**Comment by sobomax** [comment] 2015-09-17 14:42
The issue(s) should be resolved in the latest master. Thanks for reporting!

**Closed by sobomax** 2015-09-17 14:42 UTC

**Comment by sobomax** [comment] 2018-06-21 18:47
Thanks Sven for sharing your observation. I am really curious as to where
that delay might be coming from. If you can make a capture of all 4 streams
involved, perhaps we check and see where the problem might be.

-Max
